#!/usr/bin/env bash

LISUX=${LISUX:-~/.lisux}
export LISUX=$LISUX
export PATH="$LISUX/bin:$PATH"

[ -d "$LISUX/apps/pyenv" ] && {
    export PYENV_ROOT="$LISUX/apps/pyenv" 
    export PATH="$PYENV_ROOT/bin:$PATH" 
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi
}
