#!/usr/bin/env bash

LISUX=${LISUX:-~/.lisux}
export LISUX=$LISUX
export PATH="$LISUX/bin:$PATH"

[ -d "$LISUX/apps/ohmyzsh" ] && [ $ZSH_VERSION ] && {
    export ZSH="$HOME/.lisux/apps/ohmyzsh"

    ZSH_THEME="typewritten"

    source $ZSH/oh-my-zsh.sh

    plugins=(git sudo)
    plugins+=(zsh-autosuggestions)
    plugins+=(zsh-syntax-highlighting)

    export TYPEWRITTEN_PROMPT_LAYOUT="multiline"

    source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
}

[ -d "$LISUX/apps/pyenv" ] && {
    export PYENV_ROOT="$LISUX/apps/pyenv" 
    export PATH="$PYENV_ROOT/bin:$PATH" 
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi
}

[ -d "$LISUX/apps/lemacs" ] && {
    export LEMACS_HOME="$LISUX/apps/lemacs"
    export PATH="$LEMACS_HOME/bin:$PATH"
}

[ -d "$LISUX/apps/roswell" ] && {
    export ROSWELL_HOME="$LISUX/apps/roswell"
    export PATH="$ROSWELL_HOME/bin:$PATH"
}

[ -d "$LISUX/apps/nvm" ] && {
    export NVM_DIR="$LISUX/apps/nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
}

[ "$WSL_DISTRO_NAME" ] && {
    WIN_HOST=$(ip route | awk '{print $3; exit}')
    export WIN_HOST=$WIN_HOST
    export LIBGL_ALWAYS_INDIRECT=1
    export DISPLAY=$WIN_HOST:0
}

if [ $WIN_HOST ];then
    export http_proxy=http://$WIN_HOST:1081
    export https_proxy=http://$WIN_HOST:1081
    git config --global http.proxy $WIN_HOST:1081
    git config --global https.proxy $WIN_HOST:1081
else
    export http_proxy=http://localhost:1081
    export https_proxy=http://localhost:1081
    git config --global http.proxy localhost:1081
    git config --global https.proxy localhost:1081
fi
