#!/usr/bin/env bash

LISUX=${LISUX:-~/.lisux}
export LISUX=$LISUX
export PATH="$LISUX/bin:$PATH"

[ -d "$LISUX/apps/pyenv" ] && {
    export PYENV_ROOT="$LISUX/apps/pyenv" 
    export PATH="$PYENV_ROOT/bin:$PATH" 
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi
}

[ -d "$LISUX/apps/lemacs" ] && {
    export LEMACS_HOME="$LISUX/apps/lemacs"
    export PATH="$LEMACS_HOME/bin:$PATH"
}

[ "$WSL_DISTRO_NAME" ] && {
    WIN_HOST=$(ip route | awk '{print $3; exit}')
    export WIN_HOST=$WIN_HOST
    export LIBGL_ALWAYS_INDIRECT=1
    export DISPLAY=$WIN_HOST:0
}
