export ZSH="$HOME/.lisux/apps/ohmyzsh"

ZSH_THEME="typewritten"

source $ZSH/oh-my-zsh.sh

plugins=(git sudo)
plugins+=(zsh-autosuggestions)
plugins+=(zsh-syntax-highlighting)

export TYPEWRITTEN_PROMPT_LAYOUT="multiline"

source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


source "$HOME/.lisux/init"