#!/usr/bin/env bash
#
[ ! $LISUX ] && {
    echo "Lisux isn't installed, exit..."
    exit
}

source $LISUX/script/utils

[ $PACMAN ] && {
    echo "Setup arch base linux"
    yay -S kcm-fcitx fcitx-rime wqy-microhei adobe-source-han-sans-cn-fonts ttf-arphic-ukai --needed
    cp $LISUX/config/pam_environment $HOME/.pam_environment

    yay -S qv2ray v2ray --needed
    yay -S nutstore pcloud-drive --needed
    yay -S com.qq.tim.spark com.qq.weixin.spark deepin.com.dingtalk.com --needed --norebuild --noredownload
    yay -S firefox atom visual-studio-code-bin --needed
    yay -S netease-cloud-music baidunetdisk-bin ttf-wps-fonts wps-office --needed

}
