#!/usr/bin/env bash

function y-or-n-p() {
    # $1 message
    # $2 default selection
    prompt="[Y/n]"
    $2 || {
        prompt="[y/N]"
    }
    $DEBUG && {
        echo "In function y-or-n-p(1: $1, 2: $2, prompt $prompt)"
    }
    if read -r -n1 -t 9 -p "$1 $prompt?" answer;then
        case $answer in
        Y | y)
            return 0;;
        N | n)
            return 1;;
        *)
            echo "Wrong answer: $answer, return default: %2"
            $2 && {
                return 0
            }
            return 1;;
        esac
    else
        echo "Timeout, return default: $2"
        $2 && {
            return 0
        }
        return 1
    fi
}

function command-exists() {
	command -v "$@" >/dev/null 2>&1
}

function text-in-file() {
    # $1 text
    # $2 file
    grep "$1" < "$2" >/dev/null 2>&1
}

function ln-and-backup() {
    [ -e $2 ] && {
        echo "backup $2"
        mv $2 "$2.bak"
    }
    ln -s $1 $2
}

function rm-if-exist() {
    [ -e $1 ] && {
        rm -rf $1
    }
}

command-exists pacman && PACMAN=true
command-exists yum && YUM=true
command-exists apt && APT=true
command-exists apk && APK=true

[ $USER = "liszt" ] && ISME=true

[ $DEBUG ] && {
    ln-and-backup "$HOME/Temp/test" "$HOME/Temp/temp"
    rm-if-exist "$HOME/Temp/temp.bak"
}
