#!/usr/bin/env bash

[ ! $LISUX ] && {
    echo "Lisux isn't installed, exit..."
    exit
}

source $LISUX/script/utils

export LEMACS_HOME=$LISUX/apps/lemacs

function failed_checkout() {
    echo "Failed to git clone $1"
    exit
}

checkout() {
    [ -d "$2" ] || git clone --depth 1 "$1" "$2" || failed_checkout "$1"
}

function install() {
    [ -d $LEMACS_HOME ] && {
        echo "Lemacs was installed...exit"
        return
    }
    printf "Installing lemacs..."
    printf "  - cloning lemacs"
    checkout https://github.com/Liszt21/Lemacs.git "$LEMACS_HOME"
    cd "$LEMACS_HOME"
    git submodule init
    git submodule update
    [ $PACMAN ] && {
        sudo pacman -S ripgrep fd nim xclip maim graphviz gnuplot shellcheck
    }
    cd $OLDPWD
}

function uninstall() {
    printf "Uninstalling lemacs..."
    rm -rf "$LEMACS_HOME"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        lemacs install
        ;;
esac
