#!/usr/bin/env bash

# TODO: add wsl support
# TODO: support debug mode
# TODO: finish basic installition
LISUX=${LISUX:-~/.lisux}

function command_exists() {
	command -v "$@" >/dev/null 2>&1
}

function in_file() {
    grep "$1" < "$2" >/dev/null 2>&1
}

function 4pacman() {
    in_file "archlinuxcn" /etc/pacman.conf || {
        echo "  - add archlinuxcn server"
        printf "[archlinuxcn]\nServer = https://mirrors.163.com/archlinux-cn/\$arch" | sudo tee -a /etc/pacman.conf
        sudo pacman -Sy
        sudo pacman -S archlinuxcn-keyring --noconfirm
    }

    sudo pacman -S yay git vim emacs curl wget zsh base-devel python-pip neofetch --needed
}

function 4yum() {
    sudo yum install git vim emacs curl wget zsh python-pip neofetch
}

function 4apt() {
    sudo apt-get install git vim emacs curl wget zsh python-pip neofetch
}

# main process
DISTROBUTION_NAME=$(grep < /etc/os-release -e "^NAME=*" | cut -f 2 -d "\"")
echo "Hello $USER, Lisux is running in $DISTROBUTION_NAME"

command_exists yum && 4yum
command_exists pacman && 4pacman
command_exists apt && 4apt

[ "$WSL_DISTRO_NAME" ] && {
    echo "In wsl"
    [ "$USER" = "liszt" ] && [ -d "/mnt/c/Liszt/Projects/Lisux" ] && {
        echo "Is me"
        ln -s /mnt/c/Liszt/Projects/Lisux ~/.lisux
    }
}

if [ -d "$LISUX" ];then
    echo "Lisux is already installed..."
else
    git clone https://github.com/Liszt21/Lisux "$LISUX"
    find "$LISUX/bin" -not -name "*.bash" -exec chmod o+x {} \;
fi

# Setting environment
RC_FILE="$HOME/.bashrc"
[ -f ~/.zshrc ] && {
    RC_FILE="$HOME/.zshrc"
}

in_file "lisux/init" "$RC_FILE" || {
    echo "  - push init file to $RC_FILE"
    echo "source $LISUX/init" >> "$RC_FILE"
}

