#!/usr/bin/env bash

# TODO: add wsl support
# TODO: support debug mode
# TODO: finish basic installition
LISUX=${LISUX:-~/.lisux}
export LISUX=$LISUX

function 4pacman() {
    text-in-file "archlinuxcn" /etc/pacman.conf || {
        echo "  - add archlinuxcn server"
        printf "[archlinuxcn]\nServer = https://mirrors.163.com/archlinux-cn/\$arch" | sudo tee -a /etc/pacman.conf
        sudo pacman -Sy
        sudo pacman -S archlinuxcn-keyring --noconfirm
    }

    sudo pacman -S yay git vim emacs curl wget zsh base-devel python-pip neofetch --needed
}

function 4yum() {
    sudo yum install git vim emacs curl wget zsh python-pip neofetch
}

function 4apt() {
    sudo apt install git vim emacs curl wget zsh python-pip neofetch \
        make build-essential libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev \
        xz-utils tk-dev libffi-dev liblzma-dev python-openssl -y
}

function install() {
    DISTROBUTION_NAME=$(grep < /etc/os-release -e "^NAME=*" | cut -f 2 -d "\"")
    echo "Hello $USER, Lisux is running in $DISTROBUTION_NAME"

    [ "$WSL_DISTRO_NAME" ] && {
        echo "In wsl"
        [ "$USER" = "liszt" ] && [ ! -e "/mnt/c/Liszt/Projects/Lisux" ] && {
            echo "Is me"
        }
    }

    if [ -e "$LISUX" ];then
        echo "Lisux is already installed..."
    else
        git clone https://github.com/Liszt21/Lisux "$LISUX"
    fi

    cd $LISUX

    source $LISUX/script/utils

    command-exists yum && 4yum
    command-exists pacman && 4pacman
    command-exists apt && 4apt

    # Setting environment
    RC_FILE="$HOME/.bashrc"

    text-in-file "lisux/init" "$RC_FILE" || {
        echo "  - push init file to $RC_FILE"
        echo "source $LISUX/init" >> "$RC_FILE"
    }

    [ $ISME ] && {
        bash $LISUX/script/setup
        lisux install all
        pyenv install 3.7.7
        pyenv global 3.7.7
        pip install -r $LISUX/config/requirement.txt
        nvm install --lts

        git config --global user.name Liszt21
        git config --global user.email 1832666492@qq.com
        git config --global credential.helper store
    }

    cd $OLDPWD
}

function uninstall() {
    echo "Uninstall lisux"
    # TODO finish uninstall
}

if [ "$DEBUG" ];then
    echo "Debug mode"
    echo "$@"
    if y-or-n-p "test";then
        echo "typed y"
    else
        echo "typed n"
    fi
elif [ "$1" == "uninstall" ];then
    uninstall
else
    install
    source "$LISUX/init"
fi
