#!/usr/bin/env bash

[ ! $LISUX ] && {
    echo "Lisux isn't installed, exit..."
    exit
}

export NVM_DIR=$LISUX/apps/nvm

function install() {
    [ -d $NVM_DIR ] && {
        echo "Nvm is already installed..."
        return
    }
    echo "Installing nvm..."
    echo "  - cloning nvm"
    git clone https://gitee.com/mirrors/nvm.git $NVM_DIR
}

function uninstall() {
    echo "Uninstalling pyenv..."
    rm -rf "$NVM_DIR"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        ;;
esac
