#!/usr/bin/env bash
#

if [ "$NVM_DIR" ];then
    echo "$NVM_DIR"
    INSTALLED=true
else
    INSTALLED=false
    if [ "$LISUX" ];then
        echo "has lisux"
        NVM_DIR="$LISUX/apps/nvm"
    else
        echo "doesn't has lisux"
        NVM_DIR="$HOME/.nvm"
    fi
fi

function install() {
    "$INSTALLED" && {
        echo "Pyenv was installed...exit"
        exit
    }
    printf "Installing nvm..."
    printf "  - cloning nvm"
    git clone https://gitee.com/mirrors/nvm.git $NVM_DIR
}

function uninstall() {
    printf "Uninstalling pyenv..."
    rm -rf "$NVM_DIR"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        ;;
esac
