#!/usr/bin/env bash

[ ! $LISUX ] && {
    echo "Can't find LISUX"
    exit
}

source $LISUX/script/utils

export ZSH="$LISUX/apps/ohmyzsh"
export RUNZSH=no

function install() {
    sh -c "$(curl -fsSL https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh)"
    ZSH_CUSTOM="$ZSH/custom"
    # Add Themes : typewritten
    git clone https://github.com/reobin/typewritten.git $ZSH_CUSTOM/themes/typewritten
    ln -s "$ZSH_CUSTOM/themes/typewritten/typewritten.zsh-theme" "$ZSH_CUSTOM/themes/typewritten.zsh-theme"

    # Add Plugins : zsh-autosuggestions zsh-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

    [ -f "$HOME/.zshrc" ] && {
        [ -f "$HOME/.zshrc.bak" ] && {
            rm $HOME/.zshrc.bak
        }
        mv $HOME/.zshrc $HOME/.zshrc.bak
    }
    # ln -s "$LISUX/config/zshrc" "$HOME/.zshrc"
    echo "source $LISUX/init" >> $HOME/.zshrc
}

function uninstall() {
    y-or-n-p "Uninstalling ohmyzsh..." && {
        rm -rf "$ZSH"
    }
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        ;;
esac
