#!/usr/bin/env bash
#

if [ "$PYENV_ROOT" ];then
    echo "$PYENV_ROOT"
    INSTALLED=true
else
    INSTALLED=false
    if [ "$LISUX" ];then
        echo "has lisux"
        PYENV_ROOT="$LISUX/apps/pyenv"
    else
        echo "doesn't has lisux"
        PYENV_ROOT="$HOME/.pyenv"
    fi
fi

echo "$INSTALLED"
echo "$PYENV_ROOT"

function failed_checkout() {
    echo "Failed to git clone $1"
    exit
}

checkout() {
    [ -d "$2" ] || git clone --depth 1 "$1" "$2" || failed_checkout "$1"
}

function install() {
    "$INSTALLED" && {
        echo "Pyenv was installed...exit"
        exit
    }
    printf "Installing pyenv..."
    printf "  - cloning pyenv"
    checkout https://github.com/pyenv/pyenv.git "$PYENV_ROOT"
}

function uninstall() {
    printf "Uninstalling pyenv..."
    rm -rf "$PYENV_ROOT"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        ;;
esac
