#!/usr/bin/env bash

[ ! $LISUX ] && {
    echo "Lisux isn't installed"
    exit
}

source $LISUX/script/utils

export PYENV_ROOT="$LISUX/apps/pyenv"

function failed_checkout() {
    echo "Failed to git clone $1"
    exit
}

checkout() {
    [ -d "$2" ] || git clone --depth 1 "$1" "$2" || failed_checkout "$1"
}

function install() {
    [ -d $PYENV_ROOT ] && {
        echo "Pyenv is already installed..."
        return
    }

    echo "Installing pyenv..."
    echo "  - cloning pyenv"
    checkout https://github.com/pyenv/pyenv.git "$PYENV_ROOT"

    if [ -e "$HOME/.pip" ];then
        [ -d "$HOME/.pip" ] && {
            y-or-n-p "overwrite .pip config" && {
                rm -rf "$HOME/.pip"
            }
        }
        [ -L "HOME/.pip" ] && {
            rm "$HOME/.pip"
        }
    fi
    [ -e "$HOME/.pip" ] || {
        ln -s "$LISUX/config/pip" "$HOME/.pip"
    }
}

function uninstall() {
    echo "Uninstalling pyenv..."
    rm -rf "$PYENV_ROOT"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source "$LISUX/init"
        ;;
esac
