#!/usr/bin/env bash

[ ! $LISUX ] && {
    echo "Lisux isn't installed"
    exit
}

source $LISUX/script/utils

export ROSWELL_HOME="$LISUX/apps/roswell"

function install() {
    [ -d $ROSWELL_HOME ] && {
        echo "Pyenv is already installed..."
        return
    }

    [ $APT ] && {
        sudo apt-get install libcurl4-openssl-dev automake -y
    }

    [ $YUM ] && {
        sudo yum install automake libcurl-devel -y
    }

    echo "Installing roswell..."
    echo "  - cloning roswell"
    git clone -b release https://github.com/roswell/roswell.git $LISUX/cache/roswell
    cd $LISUX/cache/roswell
    sh bootstrap
    ./configure --prefix=$ROSWELL_HOME
    make
    make install
    PATH=$ROSWELL_HOME/bin:$PATH ros setup
    cd $OLDPWD
}

function uninstall() {
    echo "Uninstalling roswell..."
    rm -rf "$ROSWELL_HOME"
}

case "$1" in
    [u/U]ninstall )
        uninstall
        ;;
    * )
        install
        source $LISUX/init
        ;;
esac
